namespace RaceBoard.Common.Enums
{
    public enum Action
    {
        PrivacyPolicy_Get = 1,
        PrivacyPolicyAgreement_Get = 2,
        PrivacyPolicyAgreement_Create = 3,
        Role_Get = 4,
        HiringType_Get = 5,
        Hiring_Get = 6,
        Hiring_Create = 7,
        Hiring_Update = 8,
        Hiring_Delete = 9,
        ProjectType_Get = 10,
        Project_Get = 11,
        Project_Create = 12,
        Project_Update = 13,
        Project_Delete = 14,
        ScriptStatus_Get = 15,
        Script_Get = 16,
        Script_Create = 17,
        Script_Update = 18,
        Script_Delete = 19,
        RecordingType_Get = 20,
        ScriptItem_Get = 21,
        ScriptItem_Create = 22,
        ScriptItem_Update = 23,
        ScriptItem_Delete = 24,
        ScriptCostsTemplate_Get = 25,
        ScriptCosts_Get = 26,
        ScriptCosts_Create = 27,
        ScriptCosts_Update = 28,
        ScriptCosts_Delete = 29,
        ScriptRole_Get = 30,
        ScriptRole_Create = 31,
        ScriptRole_Update = 32,
        ScriptRole_Delete = 33,
        ScriptApproval_Get = 34,
        ScriptApproval_Create = 35,
        ApprovalStatus_Get = 36,
        ScriptImport_Get = 37,
        ScriptImport_Create = 38,
        ScriptImport_Update = 39,
        ScriptImport_Delete = 40,
        ScriptImportSettings_Get = 41,
        ScriptImportSettings_Create = 42,
        ScriptImportSettings_Update = 43,
        ScriptImportSettings_Delete = 44,
        File_Get = 45,
        File_Create = 46,
        File_Update = 47,
        File_Delete = 48,

        PaymentMethod_Get = 1,

        Payment_Get = 49,
        Payment_Create = 50,
        Payment_Update = 51,
        Payment_Delete = 52,
        PaymentComplaint_Get = 53,
        PaymentComplaint_Create = 54,
        PaymentComplaint_Update = 55,
        PaymentComplaint_Delete = 56,
        PaymentComplaintItem_Get = 57,
        PaymentComplaintItem_Create = 58,
        PaymentComplaintItem_Update = 59,
        PaymentComplaintItem_Delete = 60,

        SpreadsheetType_Get = 1,
        SpreadsheetType_Create = 1,
        SpreadsheetType_Update = 1,
        SpreadsheetType_Delete = 1,

        Spreadsheet_Get = 1,
        Spreadsheet_Create = 1,
        Spreadsheet_Update = 1,
        Spreadsheet_Delete = 1,

        StudioManagement_Get = 1,
        StudioManagement_Create = 1,
        StudioManagement_Update = 1,
        StudioManagement_Delete = 1,

        IdentificationType_Get = 1,

        Payroll_Get = 1,
        Billing_Get = 1,

        Spending_Get = 1,
        SpendingPeriod_Get = 1,

        Action_Get = 1,
        
        AuthorizationCondition_Get = 1,

        Permission_Get = 1,
        Permission_Create = 1,
        Permission_Update = 1,
        Permission_Delete = 1
    }
}